### ISSUE TITLE
EnsHofx test failing

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#265]
## Description
Looks like we missed an update from @cmgas in OOPS. Changes to the config file from [OOPS PR#453](https://github.com/JCSDA/oops/pull/453) is breaking the enshofx test. We're missing 
EnsembleApplication.members in the yaml file and possibly other things ...

See @cmgas 's changes [here](https://github.com/JCSDA/oops/blob/a131335964860a1f9121c5bf83aafdc0c9d1a0b2/src/oops/runs/EnsHofX.h#L66)

**Comment by cmgas** [comment]
Hello @guillaumevernieres ,
We changed the way the ensemble applications are done, you can look at the example [example for qg](https://github.com/JCSDA/oops/blob/develop/qg/test/testinput/ens_hofx.yaml) .

I didn't anticipate the changes with SOCA, but for all the models that had an ens_hofx test, the changes to implement are:
in `soca/test/CMakelists.txt`, add the number of MPI tasks:
```
soca_add_test( NAME enshofx
               EXE  soca_enshofx.x
               MPI  3
               NOCOMPARE
               NOTRAPFPE
               TEST_DEPENDS test_soca_enspert )
```

And in soca/test/testinput/enshofx.yml, add the lines at the beginning of the yaml:
```
EnsembleApplication:
  members: 3
```

You had no comparison test, this is not adding one but since Log::test() only writes the task 0 for now, you can only monitor the member 0. We plan on changing that.

**Comment by travissluka** [comment]
@cmgas I'm assuming that at some point in the future you all are planning to add the capability run with fewer PEs than there are number of ensemble members?

**Comment by guillaumevernieres** [comment]
Thanks for the pointers @cmgas .

**Comment by cmgas** [comment]
@travissluka yes, this will be added
