### ISSUE TITLE
Add simple generic Chl UFO to the 3D h(x) test 

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#350]
## Description
Simulate Chl from soca.

## Solution
- Add a sample viirs chl retrieval obs file
- Add the obsspace to the 3D h(x) test case

## Dependencies
#349 will need to be implemented first.

**Comment by guillaumevernieres** [comment]
@liuxiao37k or @flampouris , please assign @liuxiao37k

**Comment by liuxiao37k** [comment]
@guillaumevernieres @jkbk2004 Sorry I should have push my chl_ufo branches (one in [ufo](https://github.com/JCSDA/ufo/tree/feature/chl_ufo) and one in [soca](https://github.com/JCSDA/soca/tree/feature/chl_ufo)) earlier.
UFO/HofX for chlorophyll ‘chleuzintegr’ stands for chlorophyll euphotic layer integrated average. In this formula, the code reads in chlorophyll (3-dim) from the restart file and uses a bulk formula to estimate the euphotic layer depth (euz) based on surface chlorophyll value then averages chlorophyll over euz to be compared with satellite observations.
As a preliminary test for log-based treatments, chlorophyll observations and hofx values were both log-transformed; observation errors are typically considered as a percentage of the observed values so were here transformed to constant values given the log-based treatments; increments were applied as a multiplying factor: geovals = geovals * exp(incr_3d).
Let's please discuss these potential solutions.

**Comment by frolovsa** [comment]
@liuxiao37k Not sure i fully follow your description of chla observation operator. I am bit rusty so correct me if i am wrong or misunderstood you. Shouldn't you be comparing satellite measurements with integrated chl-a in the first optical depth instead of the euphotic depth? I am also a bit confused why you estimate of euphotic depth based on a surface chla value? Wouldn't it be more accurate to compute Zeu exactly given that you have access to the 3d chla field?
