### ISSUE TITLE
Travis-ci: atlas matching branch does not work

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#382]
## Description
Note before I forget the issue: atlas was removed from the matching branch repos in `.travis.yml`, since for some reason the correct branch would not be selected in the container. I could not reproduce the problem while building the same way travis-ci does on my desktop.
Needs to be looked at ... one day ...

**Comment by travissluka** [comment]
I think this is because atlas has a `develop` branch which TravisCI tries to use (instead of the correct `release-stable`) when soca was on the  `develop` branch.

Possible solution might be for me to modify the travis-ci script to only try to match the branches if they start with `bugfix/`, `hotfix/`, or `feature/`. We don't want branch matching to occur on `develop`, `master` or `release/` branches. As usual we have to make sure our soca feature branches are named specifically enough that they don't unintentionally match an existing branch of the same name in the other repos. This should fix the problem I think
