### ISSUE TITLE
check logic on add increment for cice/uocn/vocn

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#459]
## Description

PR #458 allows the tests to pass for upcoming oops PRs which increase increment/state coverage. In order for that to work, `cicen`, `uocn`, and `vocn` have to be omitted from the increment test.

#### For `cicen`:
The test fails because of the special way an increment is added to the state. If the background has no ice, it is not possible for the increment to add **any** ice to any of the ice categories. I'm assuming we probably want the ability for our da to add ice where there is no ice??

#### For `ucon`/`vocn`:
Seems to be failing because of the un-destaggering in add increment. I'm not sure there is any way around this given the way the tests are written, unless we move the destaggering elsewhere in the process (at read/write time?)

### To Reproduce:
- add the mentioned variables to `testinput/increment.yml`  : `inc variables` and run the increment test

**Comment by guillaumevernieres** [comment]
## u/v
Interp is not invertible, so I didn't put the de-staggering in ana2model. We are de-staggering because of B(ump), a change of variable would work, but that seems inefficient to call interp and interpad at every B multiply ... 
 
## Sea-ice 
Not easy either. We could create a separate application to "add" a sea-ice increment to a state, or maybe implement it in "checkpoint". We currently can't create ice in places where there isn't any in the background. One day.

**Comment by guillaumevernieres** [comment]
@travissluka Looks like we forgot to close this. It was fixed when we simplified our sea-ice DA ... closing!
