### ISSUE TITLE
Make BGC public 

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#597]
## Description
Check if `https://github.com/NOAA-EMC/ocean_BGC.git` can become public.

**Comment by liuxiao37k** [comment]
Request sent; waiting for EMC management's response.
@jkbk2004 @guillaumevernieres

**Comment by liuxiao37k2** [comment]
@guillaumevernieres I was informed that EMC has no requirements for releasing codes from the ocean BGC repository (https://github.com/NOAA-EMC/ocean_BGC) that SOCA currently points at. The repo is already a public repository (I just created a new GitHub account to log in and was able to clone that repository right away) so I don't see problems on the ocean BGC side with SOCA's release. I am not sure I even need to create a release tag since SOCA points to a specific commit hash when initializing the BGC submodule.

**Comment by liuxiao37k** [comment]
@guillaumevernieres I was informed that EMC has no requirements for releasing codes from the ocean BGC repository (https://github.com/NOAA-EMC/ocean_BGC) that SOCA currently points at. The repo is already a public repository (I just created a new GitHub account to log in and was able to clone that repository right away) so I don't see problems on the ocean BGC side with SOCA's release. I am not sure I even need to create a release tag since SOCA/MOM6 points to a specific commit hash when initializing the BGC submodule.

**Comment by guillaumevernieres** [comment]
Thanks for checking @liuxiao37k . All we need is for that repository to be public, so all good!
