### ISSUE TITLE
Implement 3D LETKF (add vertical obs. localization)

### ISSUE THREAD

**Issue by frolovsa** [JCSDA-internal/soca#622]
## Description
Add vertical obs. localization to the soca letkf.

## Solution
The following steps will probably need to be added. 
in oops:
[] *GeometryIterator returns point3 object not point2. 
[] Will require changes to all models, l95, qg, fv3, soca, shallow_water, neptune. 

in soca: 
[] Add 3D option to geometry iterator. 
- Probably pass the switch through the geometry object. 
- Add test to soca to test 3D iterator. 

[] Add new method int = GeometryIterator.numberOfDimensions()
[] Modify soca::increment.setLocal() and soca::increment.getLocal() to work with 3D iterator. 
[] Add new obs localization to soca. something like soca::Gc99_3D. 

## Alternatives
GETKF localization is under the development in a parallel issue. It would be nice to have two options that we can compare. Testing in the HAT10 domain will be ideal.

**Comment by frolovsa** [comment]
@travissluka i ran in to a science decision that i need help with. 
So when we iterate in 3D, we loop through all vertical levels for the 3D variables. Each level is assigned a discrete depth value. So far so good. But what happens for the 2D variables? Should one of the iterations be reserved for things like surface  2D variables with the depth assigned to 0? 
So far we have the following 2D variables= {ssh cicen hicen hsnon} all of those are on the surface, correct?

**Comment by travissluka** [comment]
yes, those are all on the surface, and so we could probably give them a depth of 0.0.

we can discuss this in person, perhaps, but it might be a good time to hash this out:
I haven't looked too closely at what you have been implementing, but Instead of thinking in terms of "levels" it might be better to think in more generic terms of "localization groups". Where it is up to the model (or more specific ObsLocalization classes) to determine the number of localization groups, and how obs are localized within those groups. 

E.g. if I want 
1) vertical localization at every level, soca would create 75 "localization groups", one for each level in the column, and modulate the localization depending on dz between grid/obs.
2) to speed things up, only create 2 "localization groups": above MLD, and below. where sst obs only impact the top group, and ssh and insitu T/S impacts both groups.
3) variable localization, expanding on number 2 above, create 3 groups, where s/T are localized independently in the top group, and they both impact the bottom group the same.

... you get the point. we would essentially have the flexibility to have locailzation be performed with  `1` to `nz*nv` groups, and anything in between, instead of hardcoding to just `nz` levels. This is essentially what I implement in a past LETKF life https://github.com/travissluka/UMD-LETKF/blob/develop/src/subclass.letkf_localizer/letkf_loc_ocean.F90

**Comment by frolovsa** [comment]
Yes. let tag up in person and post the summary here. I will send you an email in a sec.

**Comment by frolovsa** [comment]
this was addressed in https://github.com/JCSDA-internal/soca/pull/636
will open a separate issue for vertical localization
