### ISSUE TITLE
SOCA has died - "analytic init" something, something, missing.

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#637]
## Description
refusing to compile. I suspect https://github.com/JCSDA-internal/ufo/pull/1488 broke things.

```
[ 95%] Building CXX object soca/src/mains/CMakeFiles/soca_letkf.x.dir/LETKF.cc.o
/home/tsluka/work/soca/bundle/soca/src/mains/HofX.cc: In function ‘int main(int, char**)’:
/home/tsluka/work/soca/bundle/soca/src/mains/HofX.cc:24:49: error: expected primary-expression before ‘>’ token
   24 |   ufo::instantiateObsErrorFactory<ufo::ObsTraits>();
```

**Comment by travissluka** [comment]
@shlyaeva it seems @guillaumevernieres and I feel asleep in a meeting somewhere because we didn't know about these changes coming. Removing the traits from `instantiate...` is easy enough. But our getvalues test is broken and I'm not clear on how to fix it. We don't have anything `analytic init` related in our code/yamls.

**Comment by travissluka** [comment]
ah https://github.com/orgs/JCSDA-internal/teams/jedi-models/discussions/52
I should really figure out how to get notifications enable again for those things

**Comment by travissluka** [comment]
@guillaumevernieres @shlyaeva 
Since soca has no `AnalyticInit`, and we weren't using one of the ufo ones... what exactly has our getvalues interpolation test been doing this whole time?

**Comment by shlyaeva** [comment]
@travissluka please sign up for notifications on that jedi-models discussion page -- we post there when there are upcoming changes affecting models. That page isn't notifications-heavy, and those notifications are almost always very useful to know about upcoming changes.

**Comment by shlyaeva** [comment]
@travissluka we also announce the changes at JEDI, and JEDI2 meetings. If you'd like to be in JEDI2 (model interface) meetings, let me know.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @shlyaeva Since soca has no `AnalyticInit`, and we weren't using one of the ufo ones... what exactly has our getvalues interpolation test been doing this whole time?

Read a background or "invent" a state. I haven't looked at that part of the code in ages, but the issue came up again a few weeks ago when @hga007 implemented analytic init for roms-jedi.

@shlyaeva please add me to the jedi2 meetings as well ... An maybe @hga007 as well.

**Comment by hga007** [comment]
Yes, my `GetValues` test is no longer working:

**Test "interface/GetValues/testGetValuesInterpolation" failed with unhandled exception: analytic_fields does not exist in analytic init factory**

I did the refactoring that @shlyaeva recommended, and it was working, but it failed after the changes were loaded to OOPS develop branch yesterday and I issued a `make update`.

I am looking at it in the debugger.  The problem here is that there isn't an analytical initialization option for an ocean model that includes the 4D state with observations.  The only possible analytical solution that I know for the shallow water model, in the literature, is for Solitons.  We have such a test in ROMS.  I am not aware of an analytical solution for tsunamis. Anyway, you pretty much can invent anything here for the GetValue unit test, but it has to include all the state variables for which there are actual and direct observations.  The shallow water model only has SSH, and there are no direct observations for 2D velocity (barotropic or vertically integrated).  Therefore, the tsunami method for a model like MOM6 or ROMS is not that useful because it doesn't test for other state variables and vertical interpolation operators.

So, I coded the analytical solution for an oceanic front as a function of longitude, latitude, depth, and bathymetry: 

```
SUBROUTINE ana_fields (name, mask, lon, lat, z, h, value)
  ...
  SELECT CASE (TRIM(name))
    CASE ('tocn', 'sea_water_potential_temperature',                         &
          'sst',  'sea_surface_temperature')
      fac1=COS(lon*deg2rad)*COS(lat*deg2rad)/dscale
      fac2=-0.5_kind_real*U0*dscale*f*SQRT(pi)/(Tcoef*g*h)
      fac3=(fac2*erf(fac1)+T0)*(1.0_kind_real+z/h)
      value=fac3*mask
    CASE ('socn', 'sea_water_practical_salinity',                            &
          'sss',  'sea_surface_salinity')
      fac1=COS(lon*deg2rad)*COS(lat*deg2rad)/dscale
      fac2=-0.5*U0*dscale*f*SQRT(pi)/(Scoef*g*h)
      fac3=S0+(0.03_kind_real*fac1/fac2)*(2.0_kind_real-EXP(z/500.0_kind_real))
      value=fac3*mask
    CASE ('uocn', 'sea_water_zonal_velocity',                                &
          'usur', 'surface_sea_water_zonal_velocity')
      fac1=SIN(lon*deg2rad)*COS(lat*deg2rad)/dscale
      fac2=z/h
      fac3=U0*(0.5_kind_real+fac2+(0.5*fac2*fac2))*EXP(-fac1*fac1)
      value=fac3*mask
    CASE ('vocn', 'sea_water_meridional_velocity',                           &
          'vsur', 'surface_sea_water_meridional_velocity')
      fac1=COS(lon*deg2rad)*SIN(lat*deg2rad)/dscale
      fac2=z/h
      fac3=-V0*(0.5_kind_real+fac2+(0.5*fac2*fac2))*EXP(-fac1*fac1)
      value=fac3*mask
    CASE ('ssh', 'sea_surface_height')
      fac1=COS(lon*deg2rad)*SIN(lat*deg2rad)/dscale
      fac2=-U0*dscale*f*SQRT(pi)/(12.0_kind_real*g)
      fac3=1.0E+5*fac2*erf(fac1);
      value=fac3*mask
    CASE ('hocn', 'sea_floor_depth_below_sea_surface')
      value=h
    CASE ('zocn', 'level_depth')
      value=z
  END SELECT
```
  Notice that I need to use an ERF (error function) which is also available in ROMS, and it is coded as an incomplete Gamma function.  By the way, the analytical solution to Solitons includes ERF for SSH and exponentials for (ubar, vbar).

  As far as I know, all the stuff in the factory is for atmospheric models.  Perhaps, we need to add ocean methods to the factory. Thus, I have to code my own AnaliticInit Class for `method:  analytic_fields`. Everything was working nicely before the refactoring.

I will continue looking in the TotalView debugger.  Perhaps, I misunderstood some of the changes that @shlyaeva  was recommending.

**Comment by shlyaeva** [comment]
@hga007 I can take a look if you point me to your code with AnalyticInit changes.

**Comment by hga007** [comment]
@shlyaeva Great, thank you!  I am currently working with the Model Class, which it is working well and passing all the tests, except the ReForecast with no exact norms.  Therefore, I am working on the branch **feature/NLM** of `roms-jedi`.  

My `AnalyticInit.cc` is a little different from what you have for shallow water.  Maybe the problem is there:

`https://github.com/JCSDA-internal/roms-jedi/tree/feature/NLM/src/romsjedi/AnalyticInit`

**Comment by shlyaeva** [comment]
@hga007 yes, I think some additional changes are needed, in particular:

- Make `AnalyticInit` a subclass of `oops::interface::AnalyticInitBase<ufo::ObsTraits>`, and create a maker for `AnalyticInit` with desired name, used in `analytic init.method` yaml section.
- Use `Parameters` instead of `Configuration` in the `AnalyticInit` constructor. 

shallow water PR (changes in Analytic Init classes) would be a good starting point. Let me know if you have any questions; happy to assist.

**Comment by hga007** [comment]
@shlyaeva sounds good. I suspected that was the case.  I will let you know if I am successful or not.  Thank you!

**Comment by hga007** [comment]
@shlyaeva It was easy to follow what you did in the shallow-water model.  The `GetValues` unit test is now working in `roms-jedi`.  Thank you!
