### ISSUE TITLE
Use of log

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#67]
Replace the remaining use of std for output with log (trace, info, debug, ...).

**Comment by travissluka** [comment]
... resurrecting this. I think the only place I've seen  that needs to be addressed is the `Geometry::print()` method. Which, if we had been printing norms of the geometry's rossby radius field to the test stream, would have caught that pesky changing answers bug fixed in https://github.com/JCSDA/soca/pull/236)

**Comment by travissluka** [comment]
closing the oldest soca issue. sad day. goodbye
