### ISSUE TITLE
TECHX-1.1: Develop/test EDA-EnVAR (SOCA)

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#868]
## Description
Run experiments with the same configuration that were done for the regional 3dvar and letkf, but with a hybrid EDA-EnVar.
## Sub-tasks

- [x] fix any bugs we find along the way
- [x] run over the same 4 month test period and evaluate the performance

## Acceptance Criteria (Definition of Done)

- [x] (TBD)

**Comment by kbhargava** [comment]
Initial experiments (without any tuning)  show that the hybrid EDA-EnVar with 5 members reveal that hybrid EDA seem to perform better than 3dvar, LETKF (both 5 and 30 members, hybrid LETKF-EnVar (5 members) at the beginning but becomes worse than 3dVar after about 3 months of run in terms of OMB statistics, more specifically in terms of ADT OMB stats. . (images below)

![absoluteDynamicTopography_ 'adt_3a_egm2008', 'adt_3b_egm2008', 'adt_c2_egm2008', 'adt_j3_egm2008', 'adt_sa_egm2008'](https://github.com/JCSDA-internal/soca/assets/22651193/25ad140a-385e-4ab3-8b21-275f02fff7ae)



![seaSurfaceTemperature_ 'sst_viirs_npp_l3u_so025'](https://github.com/JCSDA-internal/soca/assets/22651193/6f3dd751-737f-4f4a-b877-ec8c75685e52)

**Comment by kbhargava** [comment]
We tuned our EDA experiments by trying a couple things:
1. Assigning more weight to ensemble B, 0.8 and 0.2 vs 0.5 and 0.5: This improved the SST error stats at the southern boundary of the domain which we know is because of issues with static B. Hence, assigning more weight to ensemble B improves the performance here. This also, as expected, increase the ensemble spread generally. 
2. Test setting obs error perturbation size as the ADT obs error is currently set to 0.1 m which is too high. We set the factor `obs perturbation amplitude: 0.2` which seems reasonable. This also, as expected, increase the ensemble spread generally. The performance is better than the other 2 hybrid-EDA experiments in terms for about first 3 months but then the performance degrades in terms of ADT OMB stats, though not as bed as when increasing the ensemble B weight to 80%. 
![soca-regional-2023-06-28](https://github.com/JCSDA-internal/soca/assets/22651193/2bffa0bc-cbfd-4d88-b777-3383cb55b659)


![3d_methods_socaplot_20230626](https://github.com/JCSDA-internal/soca/assets/22651193/964fee83-3c2b-4bb8-9279-6a015ae24fc7)

![absoluteDynamicTopography_ 'adt_3a_egm2008', 'adt_3b_egm2008', 'adt_c2_egm2008', 'adt_j3_egm2008', 'adt_sa_egm2008'](https://github.com/JCSDA-internal/soca/assets/22651193/5abb2f62-6353-45c6-8eca-a4fa8cbdee37)



![seaSurfaceTemperature_ 'sst_viirs_npp_l3u_so025'](https://github.com/JCSDA-internal/soca/assets/22651193/727ad1b8-5c9b-4294-a5e4-b66b41c825cf)
