### ISSUE TITLE
Add OASIM obs to the SOCA hofx ctest

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#927]
## Description
Self-explanatory. Exercise OASIM via the ctests. The O-Bs should be pretty bad given the assumptions we made up to this point.

* [ ] Identify the list of ocean variables that are required by OASIM
* [ ] add/modify the fields provided by SOCA (i.e. provide the per-category chlorophyll instead of total chlorophyll)

**Comment by travissluka** [comment]
note: The capability to add dummy atm fields has been added to soca. OASIM is now part of the soca bundle and test obs are in the data directory. This issue is ready to be worked on

**Comment by HamidehGMAO** [comment]
I have added atmospheric fields and bio-chemistry fields as constants in this branch https://github.com/JCSDA-internal/soca/tree/feature/oasim_atm_fields. Currently, I'm getting SEGFAULT error! After debugging I realized the issue is in the dimension of these fields, the size of these fields are 1D and the same as number of obs, while looking at the geoval files these fields are 2D  dimensions like " aerosol_optical_thickness(nlocs=100, nwaves=33)", I will address this after I come back from the PTO.
