### ISSUE TITLE
ctest failures on AWS Parallelcluster that mostly go away when rerunning

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/soca#947]
## Description
I am on AWS Parallelcluster using a new node type hpc6a (AMD based) - probably doesn't matter. I have observed a pattern during a few builds of jedi-bundle. In the first run through all ctests, these tests fail (all but two are soca tests, but tagging @fmahebert and @srherbener for the other two tests):
```
The following tests FAILED:
	803 - test_ioda_obsspace_out_odc_compare_aod_testdatsets_0000 (Failed)
	1552 - fv3jedi_test_tier1_letkf3d_vertloc (Timeout)
	1597 - test_soca_setcorscales (Failed)
	1599 - test_soca_parameters_bump_cor_nicas_scales (Failed)
	1602 - test_soca_enspert (Failed)
	1610 - test_soca_sqrtvertloc (Failed)
	1612 - test_soca_dirac_soca_cor_nicas_scales (Failed)
	1614 - test_soca_dirac_socahyb_cov (Failed)
	1616 - test_soca_dirac_soca_mask (Failed)
	1617 - test_soca_dirac_soca_nomask (Failed)
	1622 - test_soca_enshofx (Timeout)
	1625 - test_soca_3dvar_godas (Failed)
```
When I rerun the failed tests, only one failure remains (and this one persists, no matter how often I rerun):
```
The following tests FAILED:
	1617 - test_soca_sqrtvertloc (Failed)
```
The reason for this test failure is a reference value mismatch:
```
1617: OOPS_STATS Run end                                  - Runtime:      5.01 sec,  Memory: total:     1.07 Gb, per task: min =   532.50 Mb, max =   533.69 Mb
1617: Run: Finishing oops::SqrtOfVertLoc<SOCA> with status = 0
1617: terminate called after throwing an instance of 'oops::TestReferenceFloatMismatchError'
1617:   what():  Test reference Float mismatch @ Line:68
1617: Test Val : 4.7187035961463501e-02
1617: Ref  Val : 4.7187629982063002e-02
1617: Delta    : 5.9402059950086628e-07
1617: Relative tolerance: 4.7187332971763251e-08
1617: Absolute tolerance: 0.0000000000000000e+00
1617: Test Line: '   uocn   min=0.0471870359614635   max=0.8507511804331006   mean=0.4712163826659774'
1617: Ref Line : '   uocn   min=0.0471876299820630   max=0.8507511804330984   mean=0.4712163757674066'
1617:
1617: ===================================================================================
1617: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
1617: =   RANK 0 PID 26589 RUNNING AT hpc6a-48xlarge-dy-hpc6a-48xlarge-1
1617: =   KILLED BY SIGNAL: 6 (Aborted)
1617: ===================================================================================
1617:
1617: ===================================================================================
1617: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
1617: =   RANK 1 PID 26590 RUNNING AT hpc6a-48xlarge-dy-hpc6a-48xlarge-1
1617: =   KILLED BY SIGNAL: 9 (Killed)
1617: ===================================================================================
1/1 Test #1617: test_soca_sqrtvertloc ............***Failed    7.80 sec
```
## Solution
Wondering if there are dependencies that aren't set up correctly.

## Alternatives
Ignore and leave as is (not really an alternative)

## Related to
n/a

**Comment by fmahebert** [comment]
Information about the failure in `test_ioda_obsspace_out_odc_compare_aod_testdatsets_0000`:

On PCluster:
- When I run tests from a clean build of jedi-bundle, I see this test fail consistently.
- When I run all tests in dir `build/ioda` _after_ running `test_ioda_clean_obsspace_out_odc_files`, then this test and also its `0001` companion fail consistently
- When I run `test_ioda_clean_obsspace_out_odc_files` then `ctest -R test_ioda_obsspace_out` the tests pass consistently. This is weird, because it's in conflict with the previous two observations.
- In any case, when I rerun just `test_ioda_obsspace_out_odc_compare_aod_testdatsets_0000` after it's failed but without first running the "cleaning" test, then the test passes on the rerun

The failures are because the data file doesn't exist:
```
829: 000 2023-09-27 15:58:36 (E) Exception: File testoutput/diagout-aod-testdatasets_0000.odc does not exist.
829: /mnt/experiments-efs/skylab-v6/spack-stack-1.5.0/envs/unified-env/install/intel/2022.1.0/odc-1.4.6-2qsacoi/./bin/odc: File testoutput/diagout-aod-testdatasets_0000.odc does not exist.
829: 000 2023-09-27 15:58:36 (E) Exception: Cannot open testoutput/diagout-aod-testdatasets_0000.odc  (No such file or directory)
829: 000 2023-09-27 15:58:36 (E) ** Cannot open testoutput/diagout-aod-testdatasets_0000.odc  (No such file or directory) Caught in  (/mnt/experiments-efs/skylab-v6/spack-stack-1.5.0/cache/build_stage/ubuntu/spack-stage-eckit-1.24.4-4grr34vlkuquojq54l53nh3gg432abw5/spack-src/src/eckit/runtime/Tool.cc +32 start)
829: 000 2023-09-27 15:58:36 (E) ** Exception terminates odc
```

On my laptop, these tests pass in all the sequences described above...

This is very strange. Is it possible that the test dependencies are correct but that the `mnt/experiments-efs` filesystem is too slow to sync and sometimes the reading test doesn't yet see the file written by the writing test?

**Comment by climbfuji** [comment]
@travissluka Do you think you can address this in the remaining three days of the tech debt sprint? If not, we should move it back into the product backlog or the icebox (in case you don't care).

**Comment by climbfuji** [comment]
Closing. soca has been restructured and this is probably no longer valid
