### ISSUE TITLE
The geometry constructor hangs when running with the 1/4 deg global on 1 pe only 

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#992]
It seems to be hanging in "mesh_builder", the tests were done on Hera.

**Comment by travissluka** [comment]
It's not hanging, it's just going `reaaalllly` slow.
Here are the timings on my machine for `mesh_builder()` with the 1/4 deg grid

```
32 cores :    1 s
16 cores  :   5 s
 4 cores  :  40 s
 2 cores  : 159 s
 1 core   : 634 s
```

@fmahebert FYI, it seems the Atlas mesh builder scales REALLY well as you increase cores... but not so well if you want to scale in the other direction... toward 1 PE... because who would be crazy enough to want to do that :man_shrugging: 

@guillaumevernieres While I think that the atlas mesh_builder *should* perform better than 10 minutes on 1 core, I'm not sure if it's worth looking deeper into at this point. If need be, I could try putting in a hack to let you bypass the `mesh_builder` for the soca2cice stuff. Or, you could use this as a good excuse for us to parallelize that code??

**Comment by guillaumevernieres** [comment]
Thanks for looking into this @travissluka but no need to spend more time on trying to figure out how to run on 1 pe ... I concur with your findings, it scales well as you increase the number of pe's. I'm mostly done with the parallel implementation, planning to submit a pr later today or early next week.
